keys:
  - &server_falcon age1hjlaspck3qcknjvwnjahy90zl7zsp04ynr9u27p44g8dqqf9aseq5ncxzr
  - &server_saitama age13y59mzrlrlckjls3j3w4avxyrtre6jcnehnszpv2aummj8a0sc0sl43652
  - &server_kazuma age1c6h8l08uyktp45eartmdyy0p0x0w3pnet5dcvy4lg00guxmrq4xqdpcdfe
  - &server_akane age1peysazn863qdnquutt3gvnm60utvr7czmuq0pppnz6v6ngaepy9q4x3glm
  - &server_brim age15c06e7kj3t5vjxp7tjkal2qs655wvzgh7qy8h4rk6hpkrlzvssjqyp84zw
  - &admin_tie age1y20x3mwhjaax0q5zc9mwytuste6r02m2m2ee26sz4595u0yxtp3qpk9z4t
  - &admin_brim age1vx2a9gx2gw6720xnhk2qm2qhfnrv0jkv3z7w28xa0p8y9453m90qdgk88w
creation_rules:
  - path_regex: ^secrets/wireguard-psk\.sops\.yaml$
    key_groups:
      - age:
        - *admin_tie
        - *admin_brim
        - *server_akane
        - *server_falcon
  - path_regex: ^secrets/wireguard-pk-falcon\.sops\.yaml$
    key_groups:
      - age:
        - *admin_tie
        - *server_falcon
  - path_regex: ^secrets/wireguard-pk-akane\.sops\.yaml$
    key_groups:
      - age:
        - *admin_tie
        - *server_akane
  - path_regex: ^secrets/transmission\.sops\.yaml$
    key_groups:
      - age:
        - *admin_tie
        - *server_saitama
  - path_regex: ^secrets/mumble-server\.sops\.yaml$
    key_groups:
      - age:
        - *admin_tie
        - *server_akane
  - path_regex: ^secrets/kazuma\.sops\.yaml$
    key_groups:
      - age:
        - *admin_tie
        - *server_kazuma
  - path_regex: ^secrets/brim\.sops\.yaml$
    key_groups:
      - age:
        - *admin_tie
        - *admin_brim
        - *server_brim
