#!/usr/bin/env python3
"""Prologue setup hook, run as a phpfpm ExecStartPre.

Provisions the state directory: a self-signed TLS certificate for Postfix
STARTTLS on localhost, the patched application source tree and the runtime
configuration file.

Configuration is read from a JSON file (generated by the NixOS module) whose
path is passed as the sole argument. Secret values are referenced by path and
read at runtime so they never end up in the Nix store or the unit definition.
"""

import datetime
import json
import os
import re
import shutil
import sys
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID

OWNER = "prologue"

# Indentation of the STARTTLS line we anchor on, so the injected statement
# lines up with the surrounding PHP.
SMTP_OPTIONS = (
    "\n"
    + " " * 12
    + '$mail->SMTPOptions = ["ssl" => ["verify_peer" => false, '
    '"verify_peer_name" => false, "allow_self_signed" => true]];'
)


def generate_selfsigned_cert(cert_path: Path, key_path: Path) -> None:
    """Generate an unencrypted self-signed cert (replaces `openssl req`)."""
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, "localhost")])
    now = datetime.datetime.now(datetime.timezone.utc)
    cert = (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(name)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now)
        .not_valid_after(now + datetime.timedelta(days=3650))
        .sign(key, hashes.SHA256())
    )

    # Write the key restricted to its owner before anything can read it
    # (mirrors `openssl -nodes` followed by `chmod 0600`).
    fd = os.open(str(key_path), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "wb") as f:
        f.write(
            key.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.PKCS8,
                encryption_algorithm=serialization.NoEncryption(),
            )
        )
    os.chmod(key_path, 0o600)
    cert_path.write_bytes(cert.public_bytes(serialization.Encoding.PEM))


def patch_phpmailer(path: Path) -> None:
    """Skip TLS cert verification and disable AUTH for localhost."""
    text = path.read_text()
    text = text.replace("$mail->SMTPAuth = true;", "$mail->SMTPAuth = false;")
    text = text.replace(
        "$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;",
        "$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;" + SMTP_OPTIONS,
    )
    path.write_text(text)


def replace_in_files(www: Path, names: list[str], old: str, new: str) -> None:
    for name in names:
        path = www / name
        path.write_text(path.read_text().replace(old, new))


def patch_source(www: Path) -> None:
    for name in [
        "app/controllers/AdminController.php",
        "app/controllers/AuthController.php",
        "app/controllers/HomeController.php",
    ]:
        patch_phpmailer(www / name)

    # Patch screen sharing to include audio.
    replace_in_files(
        www,
        ["assets/js/call.js"],
        "getDisplayMedia({ video: videoConstraints, audio: false })",
        "getDisplayMedia({ video: videoConstraints, audio: true })",
    )

    # Patch 2FA email provider too.
    two_fa = www / "app/modules/2fa/email/EmailTwoFAProvider.php"
    if two_fa.exists():
        patch_phpmailer(two_fa)

    # Allow 3-character usernames (default is 4+).
    replace_in_files(
        www,
        ["app/models/User.php", "app/views/auth/register.php", "assets/js/user.js"],
        "{3,31}",
        "{2,31}",
    )
    replace_in_files(www, ["app/views/auth/register.php"], 'minlength="4"', 'minlength="3"')
    replace_in_files(
        www,
        [
            "app/controllers/InstallController.php",
            "app/controllers/AuthController.php",
            "app/views/auth/register.php",
            "app/views/settings.php",
        ],
        "4-32",
        "3-32",
    )
    # NB: config.php is intentionally not patched here. The upstream tree ships
    # only example.config.php; config.php is generated from it in main() (after
    # this function), where the same username-length patch is applied.


def set_config_value(text: str, key: str, value: str) -> str:
    """Replace a `$CONFIG_<key> = '...';` assignment with the given value.

    The value is substituted literally, so secrets containing regex
    metacharacters are handled safely.
    """
    pattern = r"\$CONFIG_" + key + r" = '.*';"
    return re.sub(pattern, lambda _m: f"$CONFIG_{key} = '{value}';", text)


def chown_recursive(path: Path) -> None:
    shutil.chown(path, user=OWNER, group=OWNER)
    if path.is_dir():
        for root, dirs, files in os.walk(path):
            for name in dirs + files:
                shutil.chown(os.path.join(root, name), user=OWNER, group=OWNER)


def main() -> None:
    config = json.loads(Path(sys.argv[1]).read_text())
    state_dir = Path(config["stateDir"])
    version = config["version"]
    src = Path(config["src"])
    www = state_dir / "www"
    version_file = state_dir / ".version"

    # Generate self-signed cert for Postfix STARTTLS on localhost.
    cert_path = state_dir / "postfix-selfsigned-cert.pem"
    key_path = state_dir / "postfix-selfsigned-key.pem"
    if not cert_path.exists():
        generate_selfsigned_cert(cert_path, key_path)

    # Ensure Caddy can traverse the state directory.
    state_dir.chmod(0o755)

    current_version = version_file.read_text().strip() if version_file.exists() else ""
    if current_version != version:
        if www.exists():
            shutil.rmtree(www)
        shutil.copytree(src / "public_html", www)
        patch_source(www)
        version_file.write_text(version + "\n")

    (www / "app" / "config").mkdir(parents=True, exist_ok=True)

    # Use example config as base (contains DATABASE_SCHEMA_SQL) and override
    # application settings.
    config_php = www / "app" / "config" / "config.php"
    shutil.copy(src / "public_html" / "app" / "config" / "example.config.php", config_php)

    db_pass = Path(config["dbPasswordFile"]).read_text().rstrip("\n")
    csrf = Path(config["csrfSecretFile"]).read_text().rstrip("\n")

    text = config_php.read_text()
    # The bundled DATABASE_SCHEMA_SQL enforces the username length, so apply the
    # 3-character-username allowance here too (otherwise the DB rejects names the
    # patched frontend accepts). Done before injecting secrets so that secret
    # values are never rewritten by these replacements.
    text = text.replace("{3,31}", "{2,31}").replace("4-32", "3-32")
    for key, value in {
        "DB_HOST": config["dbHost"],
        "DB_USER": config["dbUser"],
        "DB_PASS": db_pass,
        "DB_NAME": config["dbName"],
        "APP_URL": config["appUrl"],
        "APP_NAME": config["appName"],
        "STORAGE_FILESYSTEM_ROOT": f"{state_dir}/storage",
        "LOG_DIRECTORY": f"{state_dir}/storage/logs",
        "CSRF_SECRET": csrf,
    }.items():
        text = set_config_value(text, key, value)
    config_php.write_text(text)

    shutil.chown(config_php, user=OWNER, group=OWNER)
    config_php.chmod(0o400)

    (state_dir / "storage" / "logs").mkdir(parents=True, exist_ok=True)
    (state_dir / "storage" / "attachments").mkdir(parents=True, exist_ok=True)

    chown_recursive(www)
    chown_recursive(state_dir / "storage")
    shutil.chown(version_file, user=OWNER, group=OWNER)


if __name__ == "__main__":
    main()
